### ISSUE TITLE
Puppet4

### ISSUE THREAD

**Issue by zachfi** [voxpupuli/puppet-icinga2#199]
There are many instances where the multi-platform specific case handling could be drastically simplified by using Puppet 4 using the native hiera in modules lookup functionality. Also, I think almost all of the validate_* function use could be removed by using the native types. This would help clean up the code considerably. I'd be happy to help push this forward, though, are there any plans already for this work? 1.0 seems to be the release that just won't come, and while there is lots of clean up to do, the current version is functional enough. I do begin to wonder the value of cleaning up the module in the 3.x world when that cleanup would get much easier in a puppet4 world. Also, I can help. What thoughts do folks have on the subject?

**Comment by lesinigo** [comment]
Puppet3 is out of support like many of you know for sure: _IMHO_ it will be around only to keep alive current deployments but won't see much adoption for new ones.

If we consider this module more or less "work in progress" and still before production/release status, I don't see much value in supporting old, existing puppet deployments that probably already have some sort of monitoring system. I'd rather focus on new deployments, where you have to adopt a monitoring system or another, starting from greenfield.

At least this is what we're doing at our shop, where we are actively using this module on Puppet4 and we keep around an older in-house solution for existing Puppet3 deployments.

At least, it should target the latest Puppet 3.8 with future parser and all the other goodies (structured / trusted facts, ...), that would bring it much closer to Puppet4 level.

**Comment by bobapple** [comment]
Even there is no due date set for 1.0, it is very near. I plan to tag it this month, probably tomorrow.

This topic has been discussed before, also between @xaque208 and me. I understand the technical advantages of Puppet 4 and that Puppet 3 is end of life. However, reality shows a different picture. There are plenty of Puppet 3 environments out there and they won't update to Puppet 4 in the near future.

Furthermore, this module works pretty good with Puppet 4, so there are no technical reasons to make this module only available to the newer Puppet version. 

Probably, in some later versions this module will drop the Puppet 3 support. But it won't be in the near future.

**Comment by zachfi** [comment]
The comment about 1.0 not coming was in reference to the old module.  Apologies for that sounding somewhat pointed.  This was originally filed back in April against the dev.icinga.com tracker, and was referring to the module before the rewrite.  I posted here again to surface the issue, as the original post got no response, and the old module looks to soon be replaced by this one.  

If 1.0 is soon to release here, and the environments that are mentioned to still be running Puppet 3 require it, then those environments could continue to use the 1.x version of this module, while the master development of this module could evolve.  Does this module expect that people are using the master branch?  And if not, what is the expectation around how often users update their monitoring code.

Personally, I'm pinned to a quite old sha on the old module because I don't want to introduce instability in the piece of infrastructure responsible for telling me about the stability of my infrastructure.  I expect that others feel similarly, though I could be wrong.

If this is true of others, than why does the master branch need to be supportable on every version where the module is deployed?  Users are free to choose an older and stable version that works for them.

It is correct, that there is not a technical reason to update this module for the new version, and this module could live on in its current form until some backwards incompatible change comes along.  Until that time though, some of us could be working on moving this module to 2.x if we chose it.

**Comment by lazyfrosch** [comment]
When there is a technical need or advantage to adopting Puppet 4 only language feature that might help us with a integration, we will consider it for sure.

And maybe you should add a disclaimer that you work for Puppet, so that's not purely a technical interest, but a political. :disappointed:

Don't get me wrong, I'm always on point with running the current supported version. But we can't force users to do it.

The effort of maintaining multiple versions is just too high, when its only for supporting Puppet 4 features like types, or getting rid of some `validate_*`.

Our goal is that the module runs fine where users want to use it. If you check `.travis.yml` you will see that we want to support latest Puppet.

**Comment by dnsmichi** [comment]
I'm not a heavy Puppet user, still learning. I've been following the Puppet announcement quite closely in the recent months and was pretty much surprised how the EOL announcement of Puppet 3 went. Literally no-one at PuppetConf in San Diego had that in mind, there were some tweets about EOL last year.

I think the effort put into a migration to Puppet 4 is huge compared to the benefits you'll earn (my personal opinion). Not for my Vagrant test & dev environments but for "real" usage in production out there. While I agree on the fact that the module should support Puppet 4 sooner or later, I would keep Puppet 3 support as long as possible. Not only because there are many users out there, but also from the perspective that we as Icinga project support old distribution platforms. On those you don't need an extra repository for getting Puppet 4, or users just don't have the ability to "upgrade". Some don't even have choice, they are bound to what the management decides. 

We should carefully consider and evaluate which steps to take. Both for the users wanting the latest technology and those who prefer to stay with the current working stack.

I for myself as a soon-to-be user of this rewritten Puppet module don't want this newly developed module to break my setups anytime soon. I think our module maintainers will certainly take care about this after releasing 1.0 ❤️

**Comment by zachfi** [comment]
Thank you for the response here folks.  I do appreciate the work thats going into this module, and the momentum that its been gaining.

To clarify, @lazyfrosch I am no longer employed by Puppet, as of over a year.  Sorry if this seemed like a political ploy.  This request is purely a me-on-the-outside-as-a-puppet-user kind of request.  I'm still running infrastructure, as I did when I was at Puppet, just not for Puppet.  Now, I'm just a sysadmin who uses Puppet.

@dnsmichi I think on the module side, its about a days work to convert this to a Puppet4 only module.  The maintenance burden would go down, since the new language features and ecosystem features mean cleaner code and increase simplicity.

Is Netways supporting this module in customer environments or something?  Thats something that I hadn't considered, and would make sense to take into account the customer deployments before community desires.

Though, I'm still not clear why users wouldn't be able to keep an old version if we keep a good changelog, and clear expectations about what it means to upgrade this module to 2.x.  I think its really just about helping users graduate to Puppet 4 when they are ready.  For example, I'm sure there are still Puppet 2.x deployments out there, but almost no modules are being testing on it in the HEAD/master branch, because users can use the old version of the module that worked on, and was tested with Puppet2.

It sounds like my philosophy is in the minority here regardless.  I'll work to migrate my infrastructure(s) to this module and plan to send PRs to add support for a couple of other platforms I use.  Feel free to close the issue.  Cheers.

**Comment by dnsmichi** [comment]
Puppet isn't just "b00m, works", not even this module. You'll need to know about both worlds, Puppet and Icinga. I get that, and I feel that innovation is also needed in such a world. On the other side I'd like to keep the same spirit with supporting stable interfaces as we have been doing for years with Icinga now. This doesn't really matter whether this module is used at customer locations, Icinga partners or community members stepping by. I'd love to see more engagement over at https://www.monitoring-portal.org in terms of config management, such as this newly developed Puppet module. But therefore we also need a stable basis, with upgrade safety.

Although to keep this story short, which breaking changes to you see when switching to Puppet4?

**Comment by Tontonitch** [comment]
Hi,
Neither puppet 4 nor the future parser are supported in Red Hat Satellite (currently 6.2.5).
Consequently, it would be great if the puppet module for Icinga2 would still be compatible with Puppet 3 (>= 3.8.6 which is the current version used by Satellite).
https://github.com/Icinga/puppet-icinga2/issues/142
Best regards,
Yannick

**Comment by bobapple** [comment]
@xaque208 Thank you for the effort you are willing to put in this module, it's much appreciated. 

I'd like to ask everyone to please stop these wild accusations about political interests and this kind of stuff. This is not leading us anywhere. 

I will close this issue with the intention that we will reopen it or create a new one when heading to a Puppet 4 only module.
