### ISSUE TITLE
Add missing Spec Tests Test

### ISSUE THREAD

**Issue by SimonHoenscheid** [voxpupuli/puppet-icinga2#203]
Currently Travis does not Fail if there is no spec test for added code.

**Comment by lazyfrosch** [comment]
Are you talking about coverage?

Coverage for Puppet is merely a check if all resources in the catalog are tested for. Puppet coverage is not reliable but helpful to report.

E.g. when including external modules, or functions like `ensure_*` the detection is false.

Support for reporting it. That's easy.

But it should be part of a review to check if the PR also adds spec tests.

**Comment by SimonHoenscheid** [comment]
Yes I talk about coverage

**Comment by lazyfrosch** [comment]
To quote Travis CI docs:

https://docs.travis-ci.com/user/code-climate/#I-want-to-use-Code-Climate-with-parallel-builds

> Code Climate currently doesn’t aggregate test coverage results across multiple test runs. That means, you can’t effectively use it yet with libraries like parallel_test or parallel builds using our build matrix.

This is actually a general problem of `parallel_spec`, because it runs multiple rspec jobs. Only the combined exit codes break the test itself :)

Example output for the module:

```
Total resources:   123
Touched resources: 44
Resource coverage: 35.77%
```

If we would want to change this, we'd have to refactor all the specs so we optimize and merge them for speed...

**Comment by bobapple** [comment]
I agree that it's part of the review process to make sure there are spec tests included.
