### ISSUE TITLE
Allow specificing icinga2 version

### ISSUE THREAD

**Issue by stefanandres** [voxpupuli/puppet-icinga2#376]
## Expected Behavior
puppet-icinga2 should support specific version support.

## Current Behavior
The README.md proposes to set $manage_package to false and maintain your own set of `package { 'icinga2': ensure => $version }` resources.

## Possible Solution
* Add $version parameter (default: installed)

## Context
In a big (>3000 hosts, >45k services) setup, you want to pin the specific version to all packages and only let puppet handle this specific version to avoid breaking the setup on each new version without testing it in staging.

**Comment by baurmatt** [comment]
I've found https://github.com/Icinga/puppet-icinga2/issues/244 in which this issue was discussed before. I think the `manage_package` solution isn't sufficient as i would expect the main Puppet module of a software to handle this itself. The currently implemented way expects from the user to build a profile around this module in which he handle the package installation them self. This isn't needed if the Icinga2 module would allow to specify the package version/ensure state.

I've digged into other common Puppet modules like [puppetlabs-mysql](http://github.com/puppetlabs/puppetlabs-mysql), [puppetlabs-apache](http://github.com/puppetlabs/puppetlabs-apache), [puppetlabs-postgresql](http://github.com/puppetlabs/puppetlabs-postgresql), [puppet-elasticsearch](http://github.com/elastic/puppet-elasticsearch), ... they all offer a way to do this. Usually by configuring the `package_ensure` parameter.

Would you (the maintainers of the module) consider merging a PR which implements `package_ensure` or is this a no-go?

**Comment by lbetz** [comment]
What more I can say? No. See #244 especially the problem of updating db schemes.

**Comment by baurmatt** [comment]
Schema update is normally a problem of master/satellites. It's perfectly reasonable to build parts of your update management into Puppet. We usually do this by adding an apt::pin for the package + version.
Upgrades are then done by just updating the package version to the new one. Which then updates the pin and the `package` resource updates the package automatically.

Lets say $someone would have a setup with 3000 servers. Due to https://github.com/Icinga/icinga2/issues/3533 this $someone would probably only have two (master) servers which might need a schema upgrade. You closed this issue looking at 0,066% of those servers and ignoring that this feature might indeed be really helpful for the other 99,93%.

**Comment by stefanandres** [comment]
To add to the list of other modules where it is useful and was missing. @dnsmichi was so kind to implement it too: https://github.com/elastic/puppet-kibana/pull/5

**Comment by stefanandres** [comment]
To workaround this issue (also see #381) - one can use resource collector to implement a $version for the package in a role/profile:
```
Package <| title == 'icinga2' |> { ensure => $version }
```
