### ISSUE TITLE
Support disabling of parsing for an dictionary or array

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#419]
for all items inside of course....

**Comment by lbetz** [comment]
refers to #416

**Comment by spali** [comment]
Currently I can only imagine, to solve this by two separate parameters. Because I don't think it's possible to put the current "parsing" feature and this in the same and keep it easy to use.
Except you would differentiate the parameter at top level by type.
If a hash is provided, then just don't parse. If a string is provided use the current parsing functionality.
But this would be a breaking change for people that use the current parsing functionality below top level.

Or you just keep it as it is, because I switched to use the file class and just tag the file. Probably for more advanced stuff this is just the simplest solution.
To provide some functionality, you could just include my function from #416 into the module. And just keep it as it is.

**Comment by lbetz** [comment]
Maybe we could use a special key like 'unparse' into a hash to make sure the values of the hash aren't parsed.

**Comment by mphilipps** [comment]
I have tried working around that by using icinga2::config::fragment instead of icinga2::object::checkcommand, but now Icinga fails with Bad escape sequence found: \(.

Presumably I need to escape backslashes? Is there anything else I need to escape in a command string?


E: Found https://www.icinga.com/docs/icinga2/latest/doc/17-language-reference/#string-literals-escape-sequences

**Comment by mphilipps** [comment]
The config generation is even more broken than I expected..
The puppet String `"APT Update - dist-upgrade"` when passed to icinga2::config::service as the display_name turns into `display_name = "APT Update" - "dist-upgrade"` which leads to icinga2 complaining that I can't substract strings from each other.  
Could it be that this puppet module is doing a bit to much magic? I am inclined to bin this module and just manage Icinga with some normal puppet templates.

**Comment by lbetz** [comment]
Yes you're right. The parsing is like some magic. The reason was to do simple configuration easy. In the old module you had to quote and escape everything i.e.

vars.custom = "\"foobar\""

to get

vars.custom = "foobar"

quoted. But we won't to implement a complete icinga2 config parser. All complex things we do without parsing.

1) with a file resource  tagged by 'icinga2::config::file'
2) using the config fragment to store this fragment into a managed file (concat resource)
3) set -: as prefix to a string

Please have a look to 'Parsing Configuration' in the documentation, the README.md.

**Comment by lbetz** [comment]
"APT Update" - "dist-upgrade"

The parsing split off by every blank and the dash (-) is interpreted as an arithmetic symbol.

**Comment by mphilipps** [comment]
For now I am working around that by directly using icinga2::config::fragment and using {{{ }}} for my strings. {{{ }}} Strings don't require any additional parsing and none of my checks/descriptions contain }}}. Actually I should probably write a check for that.

**Comment by lbetz** [comment]
This won't be fixed, we have to use the prefix -: in every item of an array or values in a hashes.
