### ISSUE TITLE
Is there a way to purge exported resources?

### ISSUE THREAD

**Issue by paladox** [voxpupuli/puppet-icinga2#442]
## Expected Behavior

It should work without throwing a puppet error

## Current Behavior
When I do:

‘’’
resources { 'icinga2::object::host': purge => true, }
 resources { 'icinga2::object::service': purge => true, }
‘’’

It fails with it cannot find this resource “icinga2::object::host” same for service.

## Steps to Reproduce (for bugs)

1. Do the class like https://github.com/miraheze/puppet/blob/master/modules/icinga2/manifests/custom/conf.pp
2. Use puppet db too

## Context
We are migrating from icinga 1 to iconga2. Purging exported resources would help remove indeed hosts or services.

## Your Environment

* Module version (`puppet module list`): I copied this module including the license here https://github.com/miraheze/puppet/tree/master/modules/icinga2
* Puppet version (`puppet -V`): 4.8
* Operating System and version: Debian 9

**Comment by lbetz** [comment]
Uff, where I should start to explain... don't use this terrible implemented class.

To your problem and your question. I can't see no such objects like icinga2::object::host or icinga2::object::service so using resource doesn't make any sense.

Furthermore all icinga2 objects are implemented with concat resources. That mean if you delete an object from your code it's also removed from your icinga2 configuration. So you do not need the resources declartions.

All your icinga2 objects seem to be defined in 'static' configs and will be managed by file resources. If you wanna use file resources you can use a tag 'icinga2::config::file'. This use an implecit order and will notify the icinga2 service to reload.

The last two lines

  Icinga2::Object::Host <<||>> ~> Service['icinga2']
  Icinga2::Object::Service <<||>> ~> Service['icinga2']

are needless too because all icinga2::objects are also in the correct order automatically by the module.

Please, have a look to the example director of the icinga2 module.
