### ISSUE TITLE
Plugins from icinga exchange

### ISSUE THREAD

**Issue by famfop** [voxpupuli/puppet-icinga2#651]
I am using this repository for managing my icinga2 installation. Now I wish to install some custom checks from icinga exchange. The installation instructions I found tell "copy files to `PluginDir`". Is there a convenient way of dealing with plugins from icinga exchange with this repository? 

For example I wish to install the [Advanced Nagios Plugins Collection](https://exchange.icinga.com/harisekhon/Advanced%20Nagios%20Plugins%20Collection%20%28NoSQL%2C%20Hadoop%2C%20Redis%2C%20Cassandra%2C%20Elasticsearch%2C%20Solr%2C%20MySQL%2C%20Linux%2C%20HBase%2C%20MongoDB%20etc%29) which in turn needs an execution of `make`. How could I install this package using this repository?

Furthermore I ask myself if the checks once installed and added to a host as a service are being deployed to my satellite or do I need to install the plugins on my machines in my other zones too?

**Comment by lbetz** [comment]
Heavy question and there isn't a simple answer. Because there isn't a convenient way ...

A look into the ITL shows PluginDir is used for monitoring/nagios-plugins, PluginContribDir for nearly all other CheckCommands.

On the other hand /usr/lib/nagios/plugins or /usr/lib64/nagios/plugins should be the target for binaries from packages, direct builds from source should go to /usr/local/ e.g. nagios-plugins/libexec for monitoring plugins.

It's simple if you could split off your plugins like this, set PluginContribDir to /usr/local/nagios-plugins/libexec.

You will be get problems if you have packages for some plugins (ITL CheckCommands). But you can overload the checkcommands yourself like:

object CheckCommand "my-mem" {
  import "mem"

  command = [ MyPluginDir + "/check_mem.pl" ]
}

and use my-mem CheckCommand in yout config by setting MyPluginDir as constant.

**Comment by famfop** [comment]
Ok thank you then I will go ahead and do my own solution. Especifically the mem-check is a good example of my confusion: There is a CheckCommand already defined which was imported to Director through the kickstart wizard. Unfortunately on my system there is no check_mem.pl script. So basically now I need to go through all ITL CheckCommands and look for the ones that actually do not exist. I will probably do it successively but still I find this a big confusing!

**Comment by lbetz** [comment]
Thru the director kickstart run, all loaded checkcommands are imported and stored under external commands. That mean all external commands come from the ITL or from your running configuration if you write your own check commands in there.
