### ISSUE TITLE
Add manage_packages to replace manage_package

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#661]
in the future and add a deprecate message.

**Comment by mphilipps** [comment]
For anyone else running into this issue:
The issue here and commit should say "Add manage_packages to replace manage_package" and for time being this means you have to set both manage_packages and manage_package to false if you want to handle package installation yourself.

Feel like just straight up removing the old parameter would have been less confusing/error prone.

**Comment by lbetz** [comment]
Hm, ups.
